spring:
  application:
    name: id-generate
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:idgendb
    driver-class-name: org.h2.Driver
    username: idgendb
    password: idgendb123
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: false